"""
Django settings for Tsinghuacloud project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0xu25b&kv!!u-=+b#r2hwnm3$=ur=us(j-%ht8&%16mt&6hmi8'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'SitePages',
    'openstack_auth',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'Tsinghuacloud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Tsinghuacloud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_FINDERS = {
    'djangobower.finders.BowerFinder',
}

# Bower related configurations

BOWER_COMPONENTS_ROOT = BASE_DIR + '/components/'

# Project related
OPENSTACK_TENANT_NAME = 'admin'
OPENSTACK_USERNAME_NAME = 'admin'
OPENSTACK_PASSWORD = 'cloud'

OPENSTACK_CONTROLLER_IP = "166.111.143.238"
CEILOMETER_PORT = 8777
NOVA_PORT = 8774
ADMIN_TENANT_ID = "a7b909d0c91148d4a962a86ed472e568"
KEYSTONE_PORT = 35357

# ------- Email related -----------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Host for sending e-mail.
EMAIL_HOST = 'smtp.163.com'

# Port for sending e-mail.
EMAIL_PORT = 25

# Optional SMTP authentication information for EMAIL_HOST.
EMAIL_HOST_USER = 'tsinghuacloud@163.com'
EMAIL_HOST_PASSWORD = 'tsinghuanmcloud'
EMAIL_USE_TLS = True
#EMAIL_SUBJECT_PREFIX = u'[TsinghuaMonitor]'

##topology server
TOPO_SERVER='166.111.143.250'
TOPO_SERVER_USER='root'
TOPO_SERVER_PORT =22
TOPO_SERVER_PASSWD='tsinghuanmcloud'
TOPO_FILE='/root/res.txt'

# Site Address or IP for this application
THIS_ADDR = '166.111.143.250'

# Openstack_auth Authentication related
AUTHENTICATION_BACKENDS = ('openstack_auth.backend.KeystoneBackend',)
OPENSTACK_KEYSTONE_URL = 'http://%s:5000/v2.0' % OPENSTACK_CONTROLLER_IP
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = False
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/overview/health/'
LOGOUT_REDIRECT_URL = LOGIN_URL
OPENSTACK_API_VERSIONS = {
   "identity": 2,
}

